src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PersonRepository")
 */
class Person
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $middleName;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Grouping", inversedBy="people")
     */
    private $groupings;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $facebook;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $instagram;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $googleplus;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $snapchat;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $pinterest;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $linkedin;

    public function __construct()
    {
        $this->groupings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getMiddleName(): ?string
    {
        return $this->middleName;
    }

    public function setMiddleName(?string $middleName): self
    {
        $this->middleName = $middleName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->firstName.' '.$this->middleName.' '.$this->lastName;
    }

    public function getTitleName(): ?string
    {
        return $this->title.' '.$this->lastName;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Grouping[]
     */
    public function getGroupings(): Collection
    {
        return $this->groupings;
    }

    public function addGrouping(Grouping $grouping): self
    {
        if (!$this->groupings->contains($grouping)) {
            $this->groupings[] = $grouping;
        }

        return $this;
    }

    public function removeGrouping(Grouping $grouping): self
    {
        if ($this->groupings->contains($grouping)) {
            $this->groupings->removeElement($grouping);
        }

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(?int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getGoogleplus(): ?string
    {
        return $this->googleplus;
    }

    public function setGoogleplus(?string $googleplus): self
    {
        $this->googleplus = $googleplus;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getSnapchat(): ?string
    {
        return $this->snapchat;
    }

    public function setSnapchat(?string $snapchat): self
    {
        $this->snapchat = $snapchat;

        return $this;
    }

    public function getPinterest(): ?string
    {
        return $this->pinterest;
    }

    public function setPinterest(?string $pinterest): self
    {
        $this->pinterest = $pinterest;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }
}

src/Form/PersonType.php
<?php

namespace App\Form;

use App\Entity\Person;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class PersonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options) :void
    {
        $domain = 'form';
        $format = 'form.person.';

        $builder
            //Personal Information
            ->add('title', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
                'label_format' => $format.'%name%',
                'help' => 'A title is a prefix or suffix added to someone\'s name in 
                certain contexts. It may signify either veneration, an official position
                 or a professional or academic qualification.',
            ])
            ->add('firstName', TextType::class, [
                'required' => true,
                'translation_domain' => $domain,
                ])
            ->add('middleName', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('lastName', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('gender', ChoiceType::class, [
                'required' => true,
                'choice_translation_domain' => $domain,
                'placeholder' => 'Male or Female?',
                'choices' => [
                    'Male' => 1,
                    'Female' => 0
                ]
            ])
            ->add('address', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('birthday', DateType::class, [
                'required' => false,
                'choice_translation_domain' => $domain,
                'placeholder' => 'When was ... born',
            ])
            ->add('description', TextareaType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            //Connectivity Information
            ->add('phoneNumber', TelType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('email', TelType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('twitter', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('facebook', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('instagram', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('googleplus', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('snapchat', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('pinterest', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('linkedin', TextType::class, [
                'required' => false,
                'translation_domain' => $domain,
            ])
            ->add('save', SubmitType::class, [
                'translation_domain' => $domain,
                'label_format' => 'form.%name%',
                'attr' => [
                    'class' => 'ui right floated teal button'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver) :void
    {
        $resolver->setDefaults([
            'data_class' => Person::class,
        ]);
    }
}

src/Controller/PersonController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use App\Form\PersonType;
use App\Repository\PersonRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class PersonController extends AbstractController
{

    /**
     * @param PersonRepository $personRepository
     * @param Request $request
     * @Route("/all/{page}", name="person_index",
     * methods="GET|POST", requirements={"page"="\d+"})
     * @IsGranted("ROLE_ROOT")
     * @return Response
     */
    public function list(PersonRepository $personRepository, Request $request, $page = 1): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $locale = $request->getLocale();
        $limit = $request->get('limit') ?? 15;

        return $this->render(
            'person/index.html.twig',
            [
                'people' => $personRepository->findAllPagination($page, $limit),
                'user' => $this->getUser(),
                'page' => $page,
                'pagination' => ceil((float)$personRepository->countAll()[0]['1'] / $limit)
            ]
        );
    }

    /**
     * @param Request $request
     * @Route("/new", name="person_new", methods="GET|POST")
     * @IsGranted("ROLE_ROOT")
     * @return Response
     */
    public function new(Request $request): Response
    {
        $person = new Person();
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($person);
            $entityManager->flush();

            return $this->redirectToRoute('person_index');
        }

        return $this->render('person/new.html.twig', [
            'person' => $person,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Person $person
     * @Route("/{id}", name="person_show", methods="GET", requirements={"id"="\d+"} )
     * @IsGranted("ROLE_ROOT")
     * @return Response
     */
    public function show(Person $person): Response
    {
        return $this->render(
            'person/show.html.twig',
            [
                'person' => $person,
                'related' => $this->getDoctrine()->getRepository(Person::class)->findByRelated($person),
                'relatedGroups' =>
                    $this->getDoctrine()->getRepository(Person::class)
                    ->findByGrouping($person->getId(), $person->getGroupings()->getValues())
            ]
        );
    }

    /**
     * @param Request $request
     * @param Person $person
     * @Route("/{id}/edit", name="person_edit", methods="GET|POST")
     * @IsGranted("ROLE_ROOT")
     * @return Response
     */
    public function edit(Request $request, Person $person): Response
    {
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('person_show', ['id' => $person->getId()]);
        }

        return $this->render('person/edit.html.twig', [
            'person' => $person,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Request $request
     * @param Person $person
     * @Route("/{id}", name="person_delete", methods="DELETE")
     * @IsGranted("ROLE_ROOT")
     * @return Response
     */
    public function delete(Request $request, Person $person): Response
    {
        if ($this->isCsrfTokenValid('delete' . $person->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($person);
            $entityManager->flush();
        }

        return $this->redirectToRoute('person_index');
    }
}

templates/person/partials/related-grouping.html.twig
<div class="row">
    <div class="sixteen wide column">
        <div class="ui segments">
            <div class="ui segment">
                <h2 class="ui center aligned header">Contacts in the same group</h2>
                {% for relategroup in relatedGroups %}
                    <div class="four wide stackable fluid raised card">
                        <div class="content">
                            <div class="right floated meta">14h</div>
                            <i class="venus icon"></i> {{ relategroup.title }}
                        </div>
                        <div class="image">
                            <img src="{{ default_contact_avatar }}">
                        </div>
                        <div class="content">
                            <a class="center aligned header">{{ relategroup.firstName }} {{ relategroup.middleName }} {{ relategroup.lastName }}</a>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <a href="{{ path('person_show', {'id': relategroup.id}) }}"
                                   class="ui basic teal button">show</a>
                                <a href="{{ path('person_edit', {'id': relategroup.id}) }}"
                                   class="ui basic positive button">edit</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="ui centered card">
                        <div class="ui warning message">
                            <div class="header">No Records</div>
                            <ul class="list">
                                <li>No related contacts found</li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/person/partials/related.html.twig
<div class="row">
    <div class="sixteen wide column">
        <div class="ui segments">
            <div class="ui segment">
                <h2 class="ui centered aligned header">Related Contacts</h2>
                {% for relate in related %}
                    <div class="four wide stackable fluid raised card">
                        <div class="content">
                            <div class="right floated meta">14h</div>
                            <i class="venus icon"></i> {{ relate.title }}
                        </div>
                        <div class="image">
                            <img src="{{ default_contact_avatar }}">
                        </div>
                        <div class="content">
                            <a class="center aligned header">{{ relate.firstName }} {{ relate.middleName }} {{ relate.lastName }}</a>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <a href="{{ path('person_show', {'id': relate.id}) }}"
                                   class="ui basic teal button">show</a>
                                <a href="{{ path('person_edit', {'id': relate.id}) }}"
                                   class="ui basic positive button">edit</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="ui centered card">
                        <div class="ui warning message">
                            <div class="header">No Records</div>
                            <ul class="list">
                                <li>No related contacts found</li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/person/partials/view.html.twig
<div class="ui horizontal segments">
    <div class="ui segment">
        <div class="ui special cards">
            <div class="brown raised fluid card">
                <div class="content">
                    <div class="right floated meta">{{ person.birthday|date('d-m-Y') }}</div>
                    {{ person.titleName }}
                </div>
                <div class="blurring dimmable image">
                    <div class="ui dimmer">
                        <div class="content">
                            <div class="center">
                                <a href="{{ "/build/images/persons/#{person.slug}/avatar.jpg" }}"
                                   class="ui animated basic inverted  button" tabindex="0" data-lity
                                   data-lity-desc="Photo of a flower">
                                    <div class="visible content">{% trans %} Enlarge {% endtrans %}</div>
                                    <div class="hidden content">
                                        <i class="zoom-in icon"></i>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <img src="{{ "/build/images/persons/#{person.slug}/avatar.jpg" }}">
                </div>
                <div class="content">
                    <div class="header">Bio</div>
                    <div class="meta">About {{ person.titleName }}.</div>
                    <div class="description">
                        {{ person.description }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ui segment">
        <div class="ui brown raised fluid card">
            <div class="content">
                <div class="header">Information</div>
                <div class="meta">Personal information</div>
                <div class="ui fluid list">
                    <div class="item">
                        <i class="id card outline icon"></i>
                        <div class="content">
                            <div class="header">{{ person.title }}</div>
                            <div class="description">{{ person.fullName }}</div>
                        </div>
                    </div>
                    <div class="item">
                        <i class="phone icon"></i>
                        <div class="content">
                            <div class="header">Phone Number</div>
                            <div class="description">{{ person.phoneNumber }}</div>
                        </div>
                    </div>
                    <div class="item">
                        <i class="envelope open outline icon"></i>
                        <div class="content">
                            <div class="header">E-mail</div>
                            <div class="description">{{ person.email }}</div>
                        </div>
                    </div>
                    <div class="item">
                        <i class="envelope open outline icon"></i>
                        <div class="content">
                            <div class="header">Address</div>
                            <div class="description">{{ person.address }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ui brown raised fluid card">
            <div class="content">
                <div class="header">Social-Media</div>
                <div class="meta">External accounts</div>
                <div class="ui relaxed fluid list">
                    {% if person.facebook %}
                        <a class="item" href="https://www.facebook.com/{{ person.facebook }}" target="_blank"
                           rel="nofollow">
                            <i class="facebook icon"></i>
                            Facebook profile
                        </a>
                    {% endif %}
                    {% if person.instagram %}
                        <a class="item" href="https://instagram.com/{{ person.instagram }}" target="_blank"
                           rel="nofollow">
                            <i class="instagram icon"></i>
                            Instagram profile
                        </a>
                    {% endif %}
                    {% if person.googleplus %}
                        <a class="item" href="https://plus.google.com/{{ person.googleplus }}"
                           target="_blank" rel="nofollow">
                            <i class="google plus g icon"></i>
                            Google Plus profile
                        </a>
                    {% endif %}
                    {% if person.twitter %}
                        <a class="item" href="https://twitter.com/{{ person.twitter }}" target="_blank"
                           rel="nofollow">
                            <i class="twitter icon"></i>
                            Twitter profile
                        </a>
                    {% endif %}
                    {% if person.snapchat %}
                        <a class="item" href="https://snapchat/{{ person.snapchat }}" target="_blank"
                           rel="nofollow">
                            <i class="snapchat icon"></i>
                            Snapchat profile
                        </a>
                    {% endif %}
                    {% if person.pinterest %}
                        <a class="item" href="https://snapchat/{{ person.pinterest }}" target="_blank"
                           rel="nofollow">
                            <i class="pinterest icon"></i>
                            Pinterest board
                        </a>
                    {% endif %}
                    {% if person.linkedin %}
                        <a class="item" href="https://snapchat/{{ person.linkedin }}" target="_blank"
                           rel="nofollow">
                            <i class="linkedin icon"></i>
                            Linkedin C.V
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="ui segment">
        <div class="ui brown raised fluid card">
            <div class="content">
                <div class="header">Group(s)</div>
                <div class="meta">{{ person.titleName }}'s association.</div>
                <div class="ui fluid list">
                    {% for group in person.groupings %}
                        <div class="item">
                            <i class="{{ group.color }} {{ group.icon }} icon"></i>
                            <div class="content">
                                <div class="header">{{ group.name }}</div>
                                <div class="description">{{ group.description|slice(0, 50) }}...</div>
                            </div>
                        </div>
                    {% else %}
                        <div class="ui visible brown message">
                            <p>{{ person.titleName }} is currently not associated with any group.</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="ui horizontal segments">
    <div class="brown segment">
        <div class="ui animated fade right floated btn-third button" tabindex="0">
            <div class="visible content">Edit {{ person.titleName }} Profile</div>
            <div class="hidden content">
                Open profile editor
            </div>
        </div>
        <div class="ui animated right floated btn-primary button" tabindex="0" >
            <div class="visible content" data-lity-close>Close {{ person.titleName }} Profile</div>
            <div class="hidden content" data-lity-close>
                <i class="left arrow icon"></i>
            </div>
        </div>
        <div class="ui animated fade left floated btn-third button" tabindex="0">
            <div class="visible content">Create new contact</div>
            <div class="hidden content">
                Open profile creator
            </div>
        </div>
    </div>
</div>